### PR TITLE
Delete getHedgewareDistribution.ts

### PR DESCRIPTION
**Pull request by raykyri**
Moved over to hedgeware repo... I'd propose to delete this file to reduce the chances of someone getting confused between the two versions. Also, this doesn't work (for me) right now

### CODE REVIEW

**Comment by drewstone** [comment]
Ok, we'll fix it nonetheless and change names to generic distribution.

**Comment by drewstone** [comment]
Also it still works you just need to run with the proper config:
```
yarn script scripts/edgeware/getHedgewareDistribution.ts 
```

**Comment by raykyri** [comment]
Ok cool, maybe rename to something generic then. I'm having a hard time finding stuff between the different repos or figuring out how to run stuff - probably just because full docs haven't been finished yet

**Comment by drewstone** [comment]
Yep it’s renamed now to getQuadraticDistribution

**Pull request closed without merging**
