### PR TITLE
Move LocalEvmChain to test-utils

### PR DESCRIPTION
**Pull request by nepoche**

### CODE REVIEW

**Comment by shekohex** [comment]
Could we have this version instead? https://github.com/webb-tools/relayer/blob/main/tests/lib/localTestnet.ts it has more features and also allows for exports config files.

**Comment by shekohex** [comment]
Also would be useful to have these too in a different PR:
https://github.com/webb-tools/relayer/blob/main/tests/lib/substrateNodeBase.ts
https://github.com/webb-tools/relayer/blob/main/tests/lib/localProtocolSubstrate.ts
https://github.com/webb-tools/relayer/blob/main/tests/lib/localDkg.ts

**Comment by drewstone** [comment]
@shekohex I would recommend adding these yourself in separate PRs. This is mainly so that we can ensure the DKG tests work as is out of the box.

**Review by drewstone — COMMENTED** [review]
Status update? Can we re-format `api/package.json`?

**Review by drewstone — CHANGES_REQUESTED** [review]
This LGTM, only change I would consider making which is fine as a point of disagreement is using `bytes` rather than `bits` to count the `hexToU8a` function, since we do use byte lengths pretty standard across even those same outer function calls.

**Review by drewstone — APPROVED** [review]
LGTM

**Pull request merged**
