### PR TITLE
add @edgeware/node-types to webb.js SDK

### PR DESCRIPTION
**Pull request by shekohex**
This added support to connect to `edgeware-node` using `@edgeware/node-types` and expose a new function `optionsWithEdgeware` from `@webb-tools/api` similar to `options` function, that contains Edgeware spec.

to test it out, run `edgeware-node` from the `derw-erup-4` branch and then run

```bash
yarn script scripts/edgeware-connect.ts
```
it should connect correctly to the local edgeware node.

Relative Tasks: https://www.notion.so/hicommonwealth/edgeware-node-types-webb-js-11292ae983f3429fad0764c6c4495848

### CODE REVIEW

**Review by drewstone — APPROVED** [review]
Looks good, need to make sure it works against latest master and then we're good.

**Comment by nepoche** [comment]
I tried out the script on edgeware-node branch `drew-erup-4` with flags `--rpc-external --ws-external --rpc-cors="all" --dev" but I am running into the following error, any suggestions?: 

``` [21:11:18] , [Api]  Connecting to  ws://localhost:9944
2021-05-23 21:11:18        REGISTRY: Error: Unable to create Enum via index 13, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12
    at assert (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/util/assert.cjs:34:11)
    at createFromValue (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/types/codec/Enum.cjs:87:20)
    at decodeFromValue (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/types/codec/Enum.cjs:118:14)
    at decodeEnum (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/types/codec/Enum.cjs:142:10)
    at new Enum (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/types/codec/Enum.cjs:196:21)
    at new <anonymous> (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/types/codec/Enum.cjs:211:9)
    at new Type (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/types/create/registry.cjs:349:16)
    at decodeU8a (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/types/codec/utils/decodeU8a.cjs:24:19)
    at decodeStruct (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/types/codec/Struct.cjs:100:41)
    at new Struct (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/types/codec/Struct.cjs:134:26)
2021-05-23 21:11:18        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: Unable to create Enum via index 13, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12
2021-05-23 21:11:18        API/INIT: Error: FATAL: Unable to initialize the API: createType(Metadata):: Unable to create Enum via index 13, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12
    at EventEmitter.value (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/api/base/Init.cjs:91:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at runNextTicks (node:internal/process/task_queues:63:3)
    at processImmediate (node:internal/timers:437:9)
2021-05-23 21:11:18        API/INIT: Error: createType(Metadata):: Unable to create Enum via index 13, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12
    at createTypeUnsafe (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/types/create/createType.cjs:66:11)
    at RpcCore._formatOutput (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/rpc-core/index.cjs:387:41)
    at callWithRegistry (/Users/nathanbarnavon/workspace/web/webb.js/node_modules/@polkadot/rpc-core/index.cjs:253:42)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at runNextTicks (node:internal/process/task_queues:63:3)
    at processImmediate (node:internal/timers:437:9) ```

**Comment by drewstone** [comment]
I’m guessing we just need to update the polkadot api types in the webbjs
lib.

**Comment by shekohex** [comment]
FYI, this error happens also in the polkadot UI
try to connect to the local node built from this commit https://github.com/hicommonwealth/edgeware-node/commit/114856d7d78a81153e05dd0988b865e016de8243

https://ipfs.io/ipns/dotapps.io/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/settings/developer

So, I don't think it is an issue with our version of polkadontjs for now, since it does not work in the UI either, that means we need to add more types or we have something wrong somewhere.

**Comment by shekohex** [comment]
So after the last commit, it now works:

```bash
❯ yarn script scripts/edgeware-connect.ts                                                                                               
[16:19:21] , [Api]  Connecting to  ws://localhost:9944
[16:19:21] , [Api]  🎉 Connected to  Development
[16:19:21] , [Api]  Network Properties:  { ss58Format: '42', tokenDecimals: [ '18' ], tokenSymbol: [ 'tEDG' ] }
```

**Pull request merged**
